Blimp upgraded to 0.16.5
Backbase/golden-sample-services pull request #121
Opened 2022-01-17 07:32 UTC by pa314159

2022-01-17 08:29 UTC, jjjasper requested changes

2022-01-17 08:29 UTC, jjjasper commented on database/pom.xml
> +        <blimp-maven-plugin.version>0.16.5</blimp-maven-plugin.version>
ERROR: Plugin com.backbase.oss:blimp-maven-plugin:0.16.5 or one of its dependencies could not be resolved

2022-01-17 11:12 UTC, pa314159 commented on database/pom.xml
> +        <blimp-maven-plugin.version>0.16.5</blimp-maven-plugin.version>
Blimp published

2022-01-17 12:08 UTC, lehphyro approved these changes

2022-01-19 11:25 UTC, balazstbb approved these changes

2022-01-26 17:45 UTC, merged