Ssdk 18.0.1 update
Backbase/golden-sample-services pull request #283
Opened 2024-10-22 13:54 UTC by MalarsriA

2024-11-05 09:08 UTC, jjjasper approved these changes

2024-11-05 09:38 UTC, uesleilima requested changes

2024-11-05 09:38 UTC, uesleilima commented on services/pom.xml
> +        <testcontainers.version>1.19.7</testcontainers.version>
spring boot now manages the testcontainers dependencies version, I would remove any explicit version to it or any of its dependencies

2024-11-05 09:47 UTC, ugur-bb commented on TESTCONTAINERS.md
> +`jdbc:tc:mysql:8.0:///databasename?TC_INITFUNCTION=org.testcontainers.jdbc.JDBCDriverTest::sampleInitFunction`
We use `8.0.36` as per this RND ticket: https://backbase.atlassian.net/browse/RND-420

2024-11-05 15:00 UTC, MalarsriA commented on TESTCONTAINERS.md
> +`jdbc:tc:mysql:8.0:///databasename?TC_INITFUNCTION=org.testcontainers.jdbc.JDBCDriverTest::sampleInitFunction`
updated the PR

2024-11-05 15:01 UTC, MalarsriA commented on services/pom.xml
> +        <testcontainers.version>1.19.7</testcontainers.version>
Removed it @uesleilima

2024-11-05 21:43 UTC, ugur-bb commented on services/product/pom.xml
> +            <groupId> org.apache.activemq</groupId>
```suggestion
            <groupId>org.apache.activemq</groupId>
```

2024-11-05 21:44 UTC, ugur-bb commented on services/review/pom.xml
> +            <groupId> org.apache.activemq</groupId>
```suggestion
            <groupId>org.apache.activemq</groupId>
```

2024-11-05 21:44 UTC, ugur-bb commented on services/store/pom.xml
> +            <groupId> org.apache.activemq</groupId>
```suggestion
            <groupId>org.apache.activemq</groupId>
```

2024-11-07 09:20 UTC, uesleilima requested changes

2024-11-07 09:20 UTC, uesleilima commented on services/pom.xml
> -        <testcontainers.version>1.19.1</testcontainers.version>
if you removed this here you need also to remove the `testcontainers-bom` from the dependency manager section

2024-11-07 09:47 UTC, uesleilima approved these changes

2024-11-07 12:51 UTC, mahdieha approved these changes

2024-11-07 13:26 UTC, merged