Feature/liquibase db scripts guidelines
Backbase/golden-sample-services pull request #51
Opened 2021-01-04 12:55 UTC by torrespro

2021-01-04 13:50 UTC, eacarvalho requested changes

2021-01-04 13:50 UTC, eacarvalho commented on database/README.md
> +                    │       └── master.yml
I think README.md needs to be updated according to the structure in the code.

2021-01-04 13:50 UTC, eacarvalho commented on database/product-db/pom.xml
> +                                    <username>root</username>
All these commons configuration you can add in one section instead of repeating, example:

```
<configuration>
  <changeLogFile>${project.basedir}/src/main/resources/db/db.changelog-master.yaml</changeLogFile>
  <outputFileEncoding>UTF-8</outputFileEncoding>
  <password>backbase</password>
  <username>root</username>
</configuration>
```

2021-01-04 13:50 UTC, eacarvalho commented on database/pom.xml
> +        <java.version>11</java.version>
Given that now it is using SSDK 12 we don't need to specify `java.version` and stick to what SSDK is driving.

2021-01-04 13:50 UTC, eacarvalho commented on database/review-db/src/main/resources/liquibase.properties
> +url=jdbc:mysql://localhost:3306/review?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
Please do we need this file?

2021-01-04 13:50 UTC, eacarvalho commented on database/review-db/pom.xml
> +                            <outputChangeLogFile>${basedir}/src/main/resources/db/changelog/000-create.yaml
Please what is the thoughts behind to have `000-create.yaml` which also contains `upgrade_1_0_0_to_1_1_0`? We could have single a `master.yaml` `databaseChangeLog` which handle all database changes.

2021-01-04 13:50 UTC, eacarvalho commented on services/pom.xml
>          <boat-maven-plugin.version>0.11.3</boat-maven-plugin.version>
For me locally the project is not building, please can you take a look? Also maybe consider to use BOAT 0.12.x

`[ERROR] Failed to execute goal com.backbase.oss:boat-maven-plugin:0.11.3:bundle (bundle-specs) on project product-api: Execution bundle-specs of goal com.backbase.oss:boat-maven-plugin:0.11.3:bundle failed: Unable to fix inline examples: /Users/eduardo/Data/IdeaProjects/Backbase/golden-sample-services/api/product-api/src/main/resources/lib/examples/bad-request-validation-error.json -> [Help 1]`

2021-01-04 13:50 UTC, eacarvalho commented on api/pom.xml
> +        <groupId>com.backbase.golden-sample</groupId>
For `api` module the parent shouldn't be?

```
  <parent>
    <groupId>com.backbase.buildingblocks</groupId>
    <artifactId>backbase-openapi-spec-starter-parent</artifactId>
    <version>12.0.0</version>
    <relativePath />
  </parent>
```

2021-01-04 14:06 UTC, eacarvalho requested changes

2021-01-04 14:06 UTC, eacarvalho commented on database/product-db/src/main/resources/db/sql/mssql/create/review.sql
> +
This `review.sql` generated file doesn't belong to `product-db`, something might be wrong in the liquibase configuration.

2021-01-04 14:06 UTC, eacarvalho commented on database/product-db/src/main/resources/db/sql/oracle/create/review.sql
> +CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 5;
This `review.sql` generated file doesn't belong to `product-db`, something might be wrong in the liquibase configuration.

2021-01-04 16:40 UTC, torrespro commented on database/review-db/pom.xml
> +                            <outputChangeLogFile>${basedir}/src/main/resources/db/changelog/000-create.yaml
Because that set of changes are part of the "create" of the table, the version 1.1.0 is the index.
The changelog file grows over time if we don't define some strategy at the beginning, the changelog file will just grow bigger and bigger. On a large project, it can be a couple of thousands of lines long with hundreds of changesets. There is a high code churn on the changelog file, too, so it will cause you some merging effort.

I was trying to showcase how you can have multiple changelog files and _include_ them in the master changelog

2021-01-04 16:41 UTC, torrespro commented on database/review-db/pom.xml
> +                            <outputChangeLogFile>${basedir}/src/main/resources/db/changelog/000-create.yaml
Maybe we can find out a better split key - based on target releases perhaps?

2021-01-05 12:39 UTC, torrespro commented on database/product-db/pom.xml
> +                                    <username>root</username>
yep we were using liquibase.properties for that and then I ended copy pasting everywhere, I'll fix it

2021-01-07 11:04 UTC, eacarvalho commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
> +                  type: ${varcharDataType}(255)
I haven't used this "${varcharDataType}", please just for clarification I would like to know whether is mandatory or not to have because in case you simple use "varchar(255)" liquibase will produce the appropriated type for each database, right?

2021-01-07 11:06 UTC, eacarvalho approved these changes

2021-01-07 12:32 UTC, lehphyro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
> +            sequenceName: product_hibernate_sequence
Please follow the naming conventions at https://backbase.atlassian.net/wiki/spaces/GUIL/pages/1254162529/Database+Naming+Conventions.#DatabaseNamingConventions.-Sequences.

2021-01-07 12:32 UTC, lehphyro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
>        dbms: mysql
Shouldn't we use auto-increment for MariaDB as well since we're supposed to use exactly the same scripts as MySQL? In any case, it'd be nice to mention MariaDB in https://github.com/Backbase/golden-sample-services/blob/main/DATABASE_IDENTIFIER_STRATEGIES.md#conclusion

2021-01-07 12:32 UTC, lehphyro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
> +                  type: ${varcharDataType}(255)
Liquibase will not produce the appropriate type for each DB, this is the proper way to do it.

2021-01-07 12:32 UTC, lehphyro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.1.0.yaml
> +             indexName:  idx_create_date
Table name is missing in index name, see https://backbase.atlassian.net/wiki/spaces/GUIL/pages/1254162529/Database+Naming+Conventions.#DatabaseNamingConventions.-Indexes

2021-01-07 12:32 UTC, lehphyro commented on database/review-db/pom.xml
> +                        <version>${maven-assembly-plugin.version}</version>
This version is managed by Spring Boot so can be omitted.

2021-01-07 14:11 UTC, eacarvalho commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
> +      value: VARCHAR
Please shouldn't be varchar2 for Oracle, MySQL (MariaDB)? I was reading here: https://backbase.atlassian.net/wiki/spaces/GUIL/pages/1254162529/Database+Naming+Conventions.#DatabaseNamingConventions.-Handlingofunicode.

2021-01-08 08:17 UTC, wappers commented on api/product-api/pom.xml
> +        <groupId>com.backbase.golden-sample</groupId>
A group ID should follow Java's package name rules. The dash would make this an invalid package name.

2021-01-08 08:44 UTC, eacarvalho commented on api/product-api/pom.xml
> +        <groupId>com.backbase.golden-sample</groupId>
Yes, the description says: 

```
<xs:element name="groupId" minOccurs="0" type="xs:string">
  <xs:annotation>
    <xs:documentation source="version">3.0.0+</xs:documentation>
    <xs:documentation source="description">
      A universally unique identifier for a project. It is normal to
      use a fully-qualified package name to distinguish it from other projects with a similar name
      (eg. &lt;code&gt;org.apache.maven&lt;/code&gt;).
    </xs:documentation>
  </xs:annotation>
</xs:element>
```

And probably in our guideline we follow only "A universally unique identifier for a project" because we already have projects with dash "-" for groupId. So we are not sticking to "It is normal to use a fully-qualified package name to distinguish it".

https://backbase.atlassian.net/wiki/spaces/GUIL/pages/2020704804/Naming#Maven-Artifacts

2021-01-08 08:53 UTC, torrespro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
>        dbms: mysql
We don't support MariaDB

2021-01-08 08:57 UTC, eacarvalho commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
>        dbms: mysql
Hi Andres, when you mention that we don't support mariadb is the reason to not include in the documentation (DATABASE_IDENTIFIER_STRATEGIES.md)?

Because related to the code we already have some mariadb configuration as following:

`dbms: mssql,oracle,mariadb`

2021-01-08 09:02 UTC, torrespro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
> +            sequenceName: product_hibernate_sequence
done

2021-01-08 09:02 UTC, torrespro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
>        dbms: mysql
fixed

2021-01-08 09:03 UTC, torrespro commented on api/product-api/pom.xml
> +        <groupId>com.backbase.golden-sample</groupId>
fixed

2021-01-13 13:45 UTC, sdmoralesma commented on api/pom.xml
> +        <boat-maven-plugin.version>0.12.1</boat-maven-plugin.version>
0.13.0 already published

2021-01-13 13:48 UTC, sdmoralesma commented on database/LIQUIBASE_GUIDELINES.md
> +## Guidelines
should these guidelines be published in a confluence page?

2021-01-13 13:51 UTC, sdmoralesma commented on database/pom.xml
> +        <liquibase-maven-plugin.version>3.10.2</liquibase-maven-plugin.version>
there are breaking changes on latest version `4.2.2` should we use it or stick with 3.10.x?

2021-01-13 13:53 UTC, sdmoralesma commented on database/review-db/src/main/resources/db/generated-sql/oracle/upgrade_1_0_0_to_1_1_0/review.sql
> +ALTER TABLE review ADD stars NUMBER(3);
in our guidelines says: "Always use lowercase", should we align it here? https://backbase.atlassian.net/wiki/spaces/GUIL/pages/1254162529/Database+Naming+Conventions.

2021-01-13 14:26 UTC, ahrytsiuk commented on database/review-db/pom.xml
> +                                    <url>offline:oracle?outputLiquibaseSql=none&amp;changeLogFile=target/sql/oracle/databasechangelog.csv</url>
I remember we had some issues with SQL generated for the Oracle database. Smth was related to the `IDENTITY` generator.
We solved it by specifying a version of Oracle like this:
```
<url>offline:oracle?version=12.1.0.1&amp;changeLogFile=target/sql/oracle/changelog_master.csv</url>
``` 
It's better to add this property since it affects how scripts are generated.

Wdyt?

2021-01-13 14:26 UTC, ahrytsiuk commented on database/assembly/db-scripts.xml
> +            <outputDirectory>${artifactId}</outputDirectory>
It this case we can't use `${artifactId}`. 
Since it will result in:
```
Archive:  product-db-1.0.0-SNAPSHOT-sql.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-13-2021 16:07   product-db/
        0  01-13-2021 15:42   product-db/oracle/
        0  01-13-2021 16:07   product-db/oracle/upgrade_1_0_0_to_1_1_0/
        0  01-13-2021 16:07   product-db/oracle/create/
        0  01-13-2021 15:42   product-db/mysql/
        0  01-13-2021 16:07   product-db/mysql/upgrade_1_0_0_to_1_1_0/
        0  01-13-2021 16:07   product-db/mysql/create/
        0  01-13-2021 15:42   product-db/mssql/
        0  01-13-2021 16:07   product-db/mssql/upgrade_1_0_0_to_1_1_0/
        0  01-13-2021 16:07   product-db/mssql/create/
       68  01-13-2021 16:07   product-db/oracle/upgrade_1_0_0_to_1_1_0/product.sql
      300  01-13-2021 16:07   product-db/oracle/create/product.sql
       68  01-13-2021 16:07   product-db/mysql/upgrade_1_0_0_to_1_1_0/product.sql
      437  01-13-2021 16:07   product-db/mysql/create/product.sql
       83  01-13-2021 16:07   product-db/mssql/upgrade_1_0_0_to_1_1_0/product.sql
      310  01-13-2021 16:07   product-db/mssql/create/product.sql
```

However, by our convention folder name inside SQL artifact should be equal to the service name. So in this specific case `-db` suffix is redundant.

2021-01-13 14:26 UTC, ahrytsiuk commented on database/product-db/pom.xml
> +        <liquibase-maven-plugin.version>3.10.2</liquibase-maven-plugin.version>
We already specify these properties in the parent `database` module. Can clean-up them

2021-01-13 14:26 UTC, ahrytsiuk commented on database/product-db/pom.xml
> +        <plugins>
FYI: we can disable repackaging using property.
```
<properties>
    <spring-boot.repackage.skip>true</spring-boot.repackage.skip>
</properties>
Is equivalent to whole plugin section.

2021-01-13 14:26 UTC, ahrytsiuk commented on database/product-db/pom.xml
> +<!--                                    <labels></labels>-->
```
<labels></labels>-->
```
Line can be removed

2021-01-13 14:26 UTC, ahrytsiuk commented on database/review-db/src/main/resources/db/changelog/db.changelog-1.0.0.yaml
>              constraintName: review_unique_idx
Should we change the name to comply with the naming convention?
```
ix_review_unique
```

2021-01-13 14:42 UTC, ahrytsiuk commented on database/review-db/src/main/resources/db/generated-sql/oracle/upgrade_1_0_0_to_1_1_0/review.sql
> +ALTER TABLE review ADD stars NUMBER(3);
I think lowercase is about DB object names (tables, columns, indexes)

2021-01-13 14:48 UTC, sdmoralesma commented on database/review-db/src/main/resources/db/generated-sql/oracle/upgrade_1_0_0_to_1_1_0/review.sql
> +ALTER TABLE review ADD stars NUMBER(3);
All the examples have the objects also lowercased, e.g:
```
create table order (
  id int not null,
  order_number int constraint nn_ord_order_number not null(order_number),
  person_id int,
  constraint pk_ord_id primary key (id)
);
```
In any case would be better to clarify it @torrespro

2021-01-13 15:37 UTC, torrespro commented on database/LIQUIBASE_GUIDELINES.md
> +## Guidelines
they will be

2021-01-13 15:53 UTC, torrespro commented on database/pom.xml
> +        <liquibase-maven-plugin.version>3.10.2</liquibase-maven-plugin.version>
SSDK Persistence uses Liquibase 3.10.2 so we keep them aligned for now

2021-01-14 12:57 UTC, torrespro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.xml
> +</databaseChangeLog>
is this for rollback purposes or for what exactly?

2021-01-14 13:01 UTC, torrespro commented on database/review-db/pom.xml
> +                                    <url>offline:oracle?outputLiquibaseSql=none&amp;changeLogFile=target/sql/oracle/databasechangelog.csv</url>
I can but, IDENTITY generator it is just for MySQL not for Oracle, we should use SEQUENCE there, right?

2021-01-14 13:41 UTC, torrespro commented on database/review-db/src/main/resources/db/generated-sql/oracle/upgrade_1_0_0_to_1_1_0/review.sql
> +ALTER TABLE review ADD stars NUMBER(3);
conventions page updated to be specific

2021-01-15 15:46 UTC, eacarvalho commented on services/review/src/main/resources/application.yml
> +    hibernate.ddl-auto: none
I think this is the default value but it is nice to reiterate it.

2021-01-15 15:57 UTC, torrespro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.0.0.xml
> +</databaseChangeLog>
We will add those

2021-01-15 15:59 UTC, ahrytsiuk approved these changes

2021-01-15 15:59 UTC, torrespro commented on database/review-db/pom.xml
> +                                    <url>offline:oracle?outputLiquibaseSql=none&amp;changeLogFile=target/sql/oracle/databasechangelog.csv</url>
I'll add a ticket to review the versions we use to execute. Will merge without them for now

2021-01-18 08:37 UTC, merged