Good practice guard log statements
Backbase/golden-sample-services pull request #55
Opened 2021-01-20 12:38 UTC by maxvandewiel

- guard log statements (https://stackoverflow.com/questions/8444266/even-with-slf4j-should-you-guard-your-logging)
- Use Optional rather than null condition
- Send HTTP 201 method verb when a resource is successfully created rather than 200 
- Use functional chains for better readability
- Wrap exception handling for functional chains
- add EnableSpringDataWebSupport for paging on product list (TODO,.. paging itself can be addressed in other PR)
- set equals, hashcode and tostring in ProductEntity (https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/, https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/, https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/)

2021-01-20 13:42 UTC, torrespro commented on services/store/pom.xml
> +                                <addServletRequest>true</addServletRequest>
Is this the only reason to avoid our <goal>generate-spring-boot-embedded</goal> ? the addServlet ?
Maybe we can add it to the default in BOAT @bartveenstra will be very happy with a contribution there @maxvandewiel

2021-01-20 13:45 UTC, torrespro commented on services/store/pom.xml
> +            <version>1.18.16</version>
We have that in the dependencyManagement of the parent pom, different version also

2021-01-20 13:56 UTC, maxvandewiel commented on services/store/pom.xml
> +                                <addServletRequest>true</addServletRequest>
yes, the only reason is to have the HttpServletRequest added to the method arguments in the generated interface; this is for the POST methods to have the URI created with the resource ID suffixed in the 201 Location Header on a CREATE. If we can solve this in the BOAT plugin by 'default' I am already happy. 'Personally' is do not like the generation of the interfaces; just the POJO's would be more than sufficient for me; I like to separate the 'Router' from the 'Handlers' rather than having 'Controllers' :)

2021-01-20 13:57 UTC, maxvandewiel commented on services/store/pom.xml
> +            <version>1.18.16</version>
I will clean this up! Yes different earlier version: I will remove this one as it should not be part of my commit.

2021-01-25 11:15 UTC, eacarvalho requested changes

2021-01-25 11:15 UTC, eacarvalho commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
Here should be checking of warn is enabled?

2021-01-25 11:15 UTC, eacarvalho commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
Wondering also about "Cyclomatic complexity" and more if statements as well.

2021-01-25 11:15 UTC, eacarvalho commented on services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java
> +                getLogger().info("EXCEPTION IS {}!!!!", e);
Please is info the correct log level here?

2021-01-25 11:15 UTC, eacarvalho commented on services/product/src/main/java/com/backbase/goldensample/product/config/AppConfig.java
> +@EnableSpringDataWebSupport
Please why "EnableSpringDataWebSupport" was added?

2021-01-25 20:55 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("Service updating product {}", body);
See https://stackoverflow.com/questions/8444266/even-with-slf4j-should-you-guard-your-logging 
**In which cases would logging guards be of use?
- When there are other potential expensive operations.**

You just pass an object to `log.debug` which defers the `toString()` evaluation to only when debug is enabled. It has zero added benefit to wrap this in `isDebugEnabled`

2021-01-25 21:01 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Simulating delay of {}", delay);
See https://stackoverflow.com/questions/8444266/even-with-slf4j-should-you-guard-your-logging
**In which cases would logging guards be of use?**
**- When there are other potential expensive operations.**

You just pass an object to `log.debug` which defers the `toString()` evaluation to only when debug is enabled. It has zero added benefit to wrap this in `isDebugEnabled`

2021-01-25 21:01 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Introducing error in a %{}", faultPercent);
See https://stackoverflow.com/questions/8444266/even-with-slf4j-should-you-guard-your-logging
**In which cases would logging guards be of use?**
**- When there are other potential expensive operations.**

You just pass an object to `log.debug` which defers the `toString()` evaluation to only when debug is enabled. It has zero added benefit to wrap this in `isDebugEnabled`

2021-01-25 21:02 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("deleteProduct: tries to delete an entity with productId: {}", productId);
See https://stackoverflow.com/questions/8444266/even-with-slf4j-should-you-guard-your-logging
**In which cases would logging guards be of use?**
**- When there are other potential expensive operations.**

You just pass an object to `log.debug` which defers the `toString()` evaluation to only when debug is enabled. It has zero added benefit to wrap this in `isDebugEnabled`

(And so on for most of the other occurences in the PR... )

2021-01-25 23:01 UTC, jamespatten755 commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
It does feel like blanket-guarding against log statements in this way can sometimes detract from the readability of the code, and usually for minimal performance benefit.

2021-01-25 23:14 UTC, jamespatten755 commented on services/store/src/main/java/com/backbase/goldensample/store/api/StoreClientApiController.java
> +    private Function<Tuple2<Product, ProductAggregate>, Tuple2<Product, List<Review>>> createReviewList() {
This function feels a bit... unwieldy / difficult to follow

2021-01-26 10:02 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
The actual log statement passes the objects `faultPercent` and  `randomThreshol` and does not call expensive (or even cheap) operations. 

Wrapping this log statement has therefore zero effect.

2021-01-26 11:02 UTC, ahrytsiuk commented on services/store/pom.xml
> +                                <addServletRequest>true</addServletRequest>
In case you need access to the `HttpServletRequest` or `HttpServletResponse` you can also autowire `NativeWebRequest` into controller.

For example:
```
@RestController
public class ExampleController {

    private final NativeWebRequest nativeWebRequest;

    public ExampleController(NativeWebRequest nativeWebRequest) {
        this.nativeWebRequest = nativeWebRequest;
    }

    @PostMapping(path = "/example")
    public String example() {
        return this.nativeWebRequest.getNativeRequest(HttpServletRequest.class).getRequestURI();
    }

}
```

2021-01-26 11:51 UTC, ahrytsiuk commented on services/store/src/main/java/com/backbase/goldensample/store/api/StoreClientApiController.java
> +        return created(URI.create(request.getContextPath() + "/" + product
In this case we will get wrong URI. 
We expect smth like 
`{server.servlet.context-path}/client-api/v1/product-composite/{productId}` 
but result will be 
`{server.servlet.context-path}/{productId}` 

We can use some classes from Spring to build URI 
```
ServletUriComponentsBuilder.fromCurrentRequest()
            .pathSegment(productId)
            .build()
            .toUri()
            .getPath();
```

2021-01-26 12:09 UTC, ahrytsiuk commented on services/store/src/main/java/com/backbase/goldensample/store/api/StoreClientApiController.java
> +        return created(URI.create(request.getContextPath() + "/" + product
Add the following assert into `StoreClientApiControllerTest#shouldCreateAProductAndItsReviews` test
```
.andExpect(header().string(HttpHeaders.LOCATION, equalTo("/client-api/v1/product-composite/1")))
```

2021-01-27 08:22 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            if (MAX_SMALLER_THAN_MIN.test(min, max)) {
It is a functional coding style James and yes there is an advantage; as the predicates are isolated from the logic in which they are being used they can be tested by themselves, they are reusable in other logic, the can be bound by name in functional chains or lambda's, they can be combined and chained by themselves in which case these type of conditions do become more readable. It is not an obligation to isolate them; it is a coding style,... but not one that is invented cause it 'could' be done easier in a classical style.

2021-01-27 08:26 UTC, maxvandewiel commented on services/store/src/main/java/com/backbase/goldensample/store/api/StoreClientApiController.java
> +    private Function<Tuple2<Product, ProductAggregate>, Tuple2<Product, List<Review>>> createReviewList() {
Functions are just like other operations, they have a clear in- and output James. There pro's is that they are autonomous! They can make your code better testable as your logic becomes a 'chain' of function calls, each having a name that clearly describes the small step they are responsible for that can be tested in isolation, is reusable, can be chained and combined with other functions .... again it is a 'style' introduced since java 8 and I already noticed it is not quit inherited in the code I am looking upon.

2021-01-27 08:27 UTC, maxvandewiel commented on services/store/src/main/java/com/backbase/goldensample/store/api/StoreClientApiController.java
> +        return created(URI.create(request.getContextPath() + "/" + product
Thx for this finding; really appreciate,.. I will work on it :)

2021-01-27 08:33 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("deleteProduct: tries to delete an entity with productId: {}", productId);
Yes, the only thing is that before you pass your arguments you create a String :) the reason I come with log guard statements is that I see 'a lot of' logging in the code; on each method like a 'trace'. In general guarding log is not a bad thing and considered a good practice but you are right: everything is a trade-off as well. If we think guarding the logs is 'pre-mature optimisation' then we can decide not to make it a good practice or standard in our code and I will remove my proposition. In that case let us document that decision

2021-01-27 08:34 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Introducing error in a %{}", faultPercent);
You still  instantiated a String before you passed it to the debug method right?

2021-01-27 08:35 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Simulating delay of {}", delay);
You still instantiated a String before you passed it to the debug method right?

2021-01-27 08:35 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("Service updating product {}", body);
You still instantiated a String before you passed it to the debug method right?

2021-01-27 08:38 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/config/AppConfig.java
> +@EnableSpringDataWebSupport
thx for spotting this one :) I will remove this,... it does not belong to the scope of these changes. It was there cause I have shortly evaluated what DataWebSupport could do in regards of historical dat history but it was invalidated by me already.

2021-01-27 08:44 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
sure, it increases the complexity a little bit but please also bare in mind the coding style I observer: i.e. 'multiple return statements', 'if else coding style rather than functional coding style' ..., do these also not contribute to cyclomatic complexity? My personal observation is that readability is mainly influenced by logging a lot in debug in the first place. But I am not to impose anything; if we find initialisation of a String (as you do before you pass anything anyway) 'n' times in the primary method scopes in- and out into the heap and we find this is not something to optimise for we should decide not to have log statement guarding as our standard. In that case let us document that as such

2021-01-27 09:32 UTC, maxvandewiel commented on services/store/pom.xml
> +                                <addServletRequest>true</addServletRequest>
Only one thing with this approach: "SonarLint: A "NullPointerException" could be thrown; "getNativeRequest()" can return null." ... if we accept this NativeWebRequest is an option :)

2021-01-27 09:32 UTC, maxvandewiel commented on services/store/pom.xml
> +                                <addServletRequest>true</addServletRequest>
> Is this the only reason to avoid our generate-spring-boot-embedded ? the addServlet ?
> Maybe we can add it to the default in BOAT @bartveenstra will be very happy with a contribution there @maxvandewiel

Thanks, for the feedback :) I have refactored the change to make use again of 'generate-spring-boot-embedded' and 'NativeWebRequest' ... please bare in mind NativeWebRequest.getNativeRequest(...) might return null.

2021-01-27 09:32 UTC, maxvandewiel commented on services/store/pom.xml
> +            <version>1.18.16</version>
done

2021-01-27 09:33 UTC, maxvandewiel commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
no, the log statement logs in debug.

2021-01-27 10:23 UTC, eacarvalho commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                if (log.isDebugEnabled()) {
The code is:

```
if (log.isDebugEnabled()) {
  log.warn("Max value {} show be greater than min {}", max, min);
}
```

So we check if the debug log is enabled but we log a WARN. Is it correct?

2021-01-27 10:56 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("Service updating product {}", body);
Are you talking about the String `"Service updating product {}"` ? You are not using `new String("Service updating product {}")` therefore no new String object will be created. The String is already present in Java's String pool. Java Strings are not regular objects, they are immutable. the `log.debug` just passes the reference to the already existing String in the String pool.

2021-01-27 10:56 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Simulating delay of {}", delay);
see https://github.com/Backbase/golden-sample-services/pull/55#discussion_r565213829

2021-01-27 10:56 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +                log.debug("Introducing error in a %{}", faultPercent);
see https://github.com/Backbase/golden-sample-services/pull/55#discussion_r565213829

2021-01-27 10:56 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("deleteProduct: tries to delete an entity with productId: {}", productId);
see https://github.com/Backbase/golden-sample-services/pull/55#discussion_r565213829

2021-01-27 11:15 UTC, MarcelHeemskerk commented on services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java
> -@Slf4j
Maybe I missed a decision, but why was `@Slf4j` removed? We add Lombok to the SSDK Parent pom, and I  prefer using it's `log` instead of `getLogger()`

2021-01-27 13:21 UTC, maxvandewiel commented on services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java
> -@Slf4j
ProductCompositeService is a 'interface',... Your @Slf4J AND @Component are right in the implementation.... it is not up to the interface if AND what logger one implementer should use right? Further more,... there is no such thing as getLogger()..... assumptions are the mother of all ***

2021-01-27 13:22 UTC, maxvandewiel commented on services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java
> -@Slf4j
If you look a little bit closer you will notice that the class you refer to is suffixed with 'Impl'

2021-01-27 15:48 UTC, MarcelHeemskerk commented on services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java
> -@Slf4j
No it is in the interface `ProductCompositeService` , see https://github.com/Backbase/golden-sample-services/blob/69ac7f99996f5237b7851a100b50c9261e72bb44/services/store/src/main/java/com/backbase/goldensample/store/service/ProductCompositeService.java#L19 but you are right, I overlooked that you made it into an interface :-) 

Now your default implementation can have a NPE. Better to change that into:

```
Logger log = LoggerFactory.getLogger(ProductCompositeService.class);
```

so  in your default implementation you can again just use `log.debug(...)`

2021-02-08 16:07 UTC, jjjasper commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("Service updating product {}", body);
I am not a big fan of sending a whole `body` to the log. You are depending on a toString implementation that you don't control here and that may be changed without the realisation that its result is used to write to a log which could lead to leaking private information to the log file.

2021-02-09 14:10 UTC, MarcelHeemskerk commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            log.debug("Service updating product {}", body);
@jjjasper true, but that's a different issue: rewrite the log statement to only use the actual field you want to log.

2021-02-10 12:17 UTC, closed without merging