multi-tenancy and model extensions support
Backbase/golden-sample-services pull request #59
Opened 2021-02-08 21:07 UTC by bbzurek

added support for multi-tenancy:
   - additional DBs/users in mysql
   - users.json for auth dev with tenant users in compose file
  
added support for model extensions:
   - capturing and storing additions in review and product
   - new table and extended json messages

updated openapi specs to support additions field
  - moved definitions of used objects to `definitions.yaml` file as multiple declarations were causing duplicates in bundled specs i.e.
```
schemas:
    review:
      ...
    review_2:
      ...
```

added spring profile to use m10y mode
  - properties
  - optional variable to use when running compose: `COMPOSE_APP_PROFILE=m10y docker-compose up`
 
TODO: once ssdk 12.1.0 is available in repo can set tenant specific model extensions

2021-02-09 08:31 UTC, bbzurek commented
ok this requires a later version of `common-types` which should be published with SSDK 12.1.0 this week

2021-02-09 13:28 UTC, eacarvalho commented
Hi @bbzurek what if you also add an example for configuration isolation? I mean some property in the yaml file and retrieve the value based on header or JWT?

Then we can show how to configure it using ```@ContextScoped```.

```
test:
  property1: globalDefaultProperty1
  property1@tid(T1): value-for-tenant1
  property1@tid(T2): value-for-tenant2
```

2021-02-09 14:04 UTC, bbzurek commented
> Hi @bbzurek what if you also add an example for configuration isolation? I mean some property in the yaml file and retrieve the value based on header or JWT?

yup that was the main driver for this change, just waiting for 12.1.0 with fixes for tenat specific configs (as mentioned in TODO)

2021-02-11 11:40 UTC, lehphyro commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
We should make `product_additions_id` and `property_key` primary key in this table and add a foreign key referring to the product table.

2021-02-11 11:40 UTC, lehphyro commented on database/review-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
Please add PK and FK here as well.

2021-02-11 11:40 UTC, lehphyro commented on docker-compose.yaml
> +      JAVA_TOOL_OPTIONS: -Dlogging.level.com.backbase.buildingblocks.communication.http.InterServiceLogger=DEBUG
A regular env var should work fine: `logging.level.com.backbase.buildingblocks.communication.http.InterServiceLogger: DEBUG`

2021-02-11 11:40 UTC, lehphyro commented on services/product/src/main/java/com/backbase/goldensample/product/persistence/ProductEntity.java
> +    @ElementCollection(fetch = FetchType.EAGER)
`EAGER` fetching may cause performance issues, we should leave it as default `LAZY`.

2021-02-11 11:40 UTC, lehphyro commented on services/product/src/test/java/com/backbase/goldensample/product/api/ProductServiceApiControllerMultitenancyTest.java
> +    void shouldFailWithUnrecognisedAdditionsForTenant1() throws Exception {
Maybe rename to `shouldFailWithUnrecognisedAdditionsForTenantOrgShop`?

2021-02-11 11:40 UTC, lehphyro commented on services/product/src/test/resources/application-m10y.yml
> +          url: jdbc:tc:mysql:5.7:///test
Shouldn't the database be different?

2021-02-11 11:40 UTC, lehphyro commented on services/store/src/test/java/com/backbase/goldensample/store/api/StoreClientApiControllerAdditionsTest.java
> +@TestPropertySource(properties = {
Perhaps this can be moved to its own config file to make it easier to maintain and reuse?

2021-02-11 11:40 UTC, lehphyro commented on api/product-api/src/main/resources/product-integration-api-v1.yaml
> +              $ref: 'schemas/definitions.yaml#/components/schemas/Product'
The PR would be easier to review if this refactoring was done in a different one :)

2021-02-11 11:45 UTC, danielabeledo commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
do we really need a new table? Isn't the flattening of the Data Model Extensions something already agreed?

2021-02-11 12:11 UTC, bbzurek commented on api/product-api/src/main/resources/product-integration-api-v1.yaml
> +              $ref: 'schemas/definitions.yaml#/components/schemas/Product'
yeh sorry, I encountered some issues with the specs, but should've kept the changes to minimum instead of going all in

2021-02-11 12:12 UTC, bbzurek commented on database/review-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
I did attempt setting up a foreign key however the table is partitioned, so the foreign key constraint doesn't seem to be supported in this case

2021-02-11 12:14 UTC, bbzurek commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
I don't mind either way, I thought maybe for demonstration purposes it's easier to see the data separation that way

2021-02-11 12:17 UTC, bbzurek commented on docker-compose.yaml
> +      JAVA_TOOL_OPTIONS: -Dlogging.level.com.backbase.buildingblocks.communication.http.InterServiceLogger=DEBUG
yup I was thinking that, but I suppose I was just looking for an excuse to slot in`JAVA_TOOL_OPTIONS` in case we ever need it to supply some other params in the future, but then it should be added then, so will revert that

2021-02-15 08:30 UTC, christopherm-backbase commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
We should go with the current agreed approach.

2021-02-17 13:02 UTC, jjjasper requested changes
This example stores model extensions in a separate table. There was a decision to store as json in a lob.

(https://backbase.atlassian.net/wiki/spaces/GUIL/pages/968786809/Storing+model+extensions.)

2021-02-18 20:09 UTC, bbzurek commented on database/product-db/src/main/resources/db/generated-sql/mssql/upgrade_1_1_0_to_1_2_0/product_additions.sql
> +CREATE TABLE product_additions (product_additions_id bigint NOT NULL, property_value nvarchar(255), property_key nvarchar(50) NOT NULL)
reverted to a single column

2021-02-18 20:09 UTC, bbzurek commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
done

2021-02-18 20:10 UTC, bbzurek commented on services/store/src/test/java/com/backbase/goldensample/store/api/StoreClientApiControllerAdditionsTest.java
> +@TestPropertySource(properties = {
moved properties to a test profile

2021-02-18 20:10 UTC, bbzurek commented on services/product/src/test/resources/application-m10y.yml
> +          url: jdbc:tc:mysql:5.7:///test
updated

2021-02-18 20:10 UTC, bbzurek commented on services/product/src/test/java/com/backbase/goldensample/product/api/ProductServiceApiControllerMultitenancyTest.java
> +    void shouldFailWithUnrecognisedAdditionsForTenant1() throws Exception {
renamed

2021-02-18 20:10 UTC, bbzurek commented on services/product/src/main/java/com/backbase/goldensample/product/persistence/ProductEntity.java
> +    @ElementCollection(fetch = FetchType.EAGER)
n/a since switching to a single column approach

2021-02-18 20:10 UTC, bbzurek commented on docker-compose.yaml
> +      JAVA_TOOL_OPTIONS: -Dlogging.level.com.backbase.buildingblocks.communication.http.InterServiceLogger=DEBUG
updated

2021-02-18 20:10 UTC, bbzurek commented on database/review-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
n/a since switching to a single column approach

2021-02-18 20:11 UTC, bbzurek commented on database/product-db/src/main/resources/db/changelog/db.changelog-1.2.0.yaml
> +        - createTable:
n/a since switching to a single column approach

2021-02-19 08:28 UTC, sdmoralesma commented on services/product/src/main/java/com/backbase/goldensample/product/mapper/MapToJsonConverter.java
> +    private static final TypeReference<Map<String, String>> MAP_OF_STRINGS_TYPE_REFERENCE =
consider to inline it, looks like an inexpensive object to be created and there are not external references to it. This is similar to having `private static final ONE=1`, there is no much utility on having it.

2021-02-19 08:33 UTC, sdmoralesma commented on services/product/src/test/java/com/backbase/goldensample/product/persistence/PersistenceIT.java
> +    ProductEntity entity = new ProductEntity("amazon", 1, TODAY, Collections.singletonMap("popularity","87%"));
now we have on java9+ `Map.of("popularity","87%")` that returns an immutable map

2021-02-19 08:34 UTC, sdmoralesma commented on services/product/src/test/java/com/backbase/goldensample/product/persistence/PersistenceIT.java
> +    ProductEntity newEntity = new ProductEntity("n", 2, TODAY, Collections.singletonMap("popularity","15%"));
consider `Map.of`

2021-02-19 08:37 UTC, sdmoralesma commented on services/store/src/test/java/com/backbase/goldensample/store/api/StoreClientApiControllerAdditionsTest.java
> +        String requestBody = "{\n" +
writing json this way is kind of difficult to maintain and does not compose well. Consider to create a factory of fixtures, for example: ProductRequestFixtures#createValidRequest and internally using the  `ObjectNode` Jackson's API: `ObjectNode req = mapper.createObjectNode();` in this way you can later create complex json payloads chaining attributes to it and also tends to be easier to read.

2021-02-19 08:38 UTC, sdmoralesma approved these changes

2021-02-19 08:56 UTC, danielabeledo commented on services/product/src/main/java/com/backbase/goldensample/product/mapper/MapToJsonConverter.java
> +    private static final TypeReference<Map<String, String>> MAP_OF_STRINGS_TYPE_REFERENCE =
I am not sure about this one, because what it is being created here is an **anonymous** **subclass** of TypeReference and it would hold a reference to the outer class. I am unsure of the implications of creating a new 
```
        new TypeReference<Map<String, String>>() {}
```
each time 
```
return objectMapper.readValue(dbData, new TypeReference<Map<String, String>>() {});
```
is called

I think I remember Sonar used to complain about this exact thing

2021-02-19 09:49 UTC, bbzurek commented on services/store/src/test/java/com/backbase/goldensample/store/api/StoreClientApiControllerAdditionsTest.java
> +        String requestBody = "{\n" +
tbh I don't really agree with this aproach for posting the data to an endpoint in a test, but I can see it could work that way too :)

2021-02-19 11:15 UTC, christopherm-backbase commented on services/product/src/main/java/com/backbase/goldensample/product/mapper/MapToJsonConverter.java
> +    private static final TypeReference<Map<String, String>> MAP_OF_STRINGS_TYPE_REFERENCE =
As this a subclass, not just an instance, it would be best not to create it every time.

2021-02-19 13:38 UTC, sdmoralesma approved these changes

2021-02-23 11:25 UTC, lehphyro approved these changes

2021-02-24 14:52 UTC, christopherm-backbase approved these changes

2021-02-25 09:50 UTC, merged