Improve compatibility with IDEs plus mention lombok plugin requirement
Backbase/golden-sample-services pull request #76
Opened 2021-04-12 11:16 UTC by balazstbb

- build helper plugin added to attache OpenAPI generated sources
- gitignore extended with Theia IDE support
- documentation (README.md) IDE section extended the information lombok plugin is required

2021-04-13 16:51 UTC, torrespro requested changes
Balazs could you review why the build is failing? looks like the SSDK is not in repo yet? or it was not...

2021-04-14 07:16 UTC, balazstbb commented
hm, interesting.... this should pull dependencies from backbase repo and that is private.... I have not changed anything with it... I do not know how is suppose to connect to backbase maven repo

2021-04-14 12:15 UTC, torrespro commented
so the other builds worked, with the same settings and Maven username and pass, so it must be something else

2021-06-12 11:45 UTC, pa314159 requested changes

2021-06-12 11:45 UTC, pa314159 commented on .gitignore
> +
All these dots can be specified by the following patterns
```
.*
!.git?*
!.mvn/

```

2021-06-12 11:45 UTC, pa314159 commented on services/review/pom.xml
> +                            <goal>add-source</goal>
Boat already supports `addCompileSourceRoot` which defaults to true, isn't it enough?

2021-06-14 10:49 UTC, balazstbb commented on services/review/pom.xml
> +                            <goal>add-source</goal>
Did not work, I tried with Eclipse and with Theia (VSCode), unless I attached the additional sources with build-helper plugin I have compile errors in my IDE (the code compiles of course, but the IDE can not pick it up)

2021-06-15 20:09 UTC, closed without merging