Use BLIMP to generate SQL scripts
Backbase/golden-sample-services pull request #79
Opened 2021-06-12 11:08 UTC by pa314159

Migrate the `generateSQL` profile to BLIMP

- databases: mssql, mysql, oracle
- strip comments from output
- create SQL archive

2021-06-14 08:01 UTC, jjjasper requested changes

2021-06-14 08:01 UTC, jjjasper commented on database/pom.xml
> +        <profile>
Can you add comment what this profile is for?

2021-06-14 09:50 UTC, polarfish requested changes

2021-06-14 09:50 UTC, polarfish commented on database/pom.xml
> +        <hibernate-core.version>5.4.32.Final</hibernate-core.version>
Can we rely on `spring-boot-dependencies` starter defining `<hibernate.version>5.4.28.Final</hibernate.version>`?

2021-06-14 09:50 UTC, polarfish commented on database/pom.xml
> +        <profile>
I think the name of the profile is confusing.

2021-06-14 14:28 UTC, eacarvalho commented on database/product-db/pom.xml
> +                        <artifactId>blimp-maven-plugin</artifactId>
Hi @pa314159! Please can you explain how the contexts are being used? For example, previously we used to have `contexts="upgrade_2021.07_to_2021.08"` and this is used to generate folders with SQL Files. Did you check the files generated?

2021-06-14 14:37 UTC, eacarvalho commented on database/pom.xml
> +                                <goal>assemble</goal>
It is a bit confuse now, the source of truth is the zip file which we can extract and validate it because we still have generated-sql in the source code but not used anymore.

Btw, the structure in the zip doesn't seem correct due to some contexts issue. Please can you review this part?

`/golden-sample-services/database/product-db/src/main/resources/db/generated-sql/mysql/create/product.sql`

2021-06-14 15:10 UTC, pa314159 commented on database/product-db/pom.xml
> +                        <artifactId>blimp-maven-plugin</artifactId>
The name `upgrade_2021.07_to_2021.08` is not compliant, it should be `upgrade_2021_07_to_2021_08`.

The `initial_...` shouldn't be created, but I'll correct it in Blimp

2021-06-14 15:29 UTC, pa314159 commented on database/pom.xml
> +                                <goal>assemble</goal>
Can you elaborate a bit, @eacarvalho?

AFAIK there are teams that are still pushing generated-sql in git, that's the reason I didn't touch them.

See my other answer to the "context" problem.

2021-06-14 15:33 UTC, pa314159 commented on database/pom.xml
> +        <hibernate-core.version>5.4.32.Final</hibernate-core.version>
Done

2021-06-14 15:34 UTC, pa314159 commented on database/pom.xml
> +        <profile>
I added comment explaining what this profile is for. If you think to a different name, just let me know.

2021-06-14 18:22 UTC, pa314159 commented on database/product-db/pom.xml
> +                        <artifactId>blimp-maven-plugin</artifactId>
Use blimp-0.15.1

2021-06-14 18:25 UTC, pa314159 commented on database/product-db/pom.xml
> +                        <artifactId>blimp-maven-plugin</artifactId>
The format of the SQL name is explained in the [README](https://github.com/Backbase/blimp/blob/devel/README.md#available-parameters)

2021-06-15 07:14 UTC, eacarvalho commented on database/pom.xml
> +                        <stripComments>true</stripComments>
Hi @pa314159! Looks better now with new plugin version but we need one more config here to change the sql script file name, has to be product.sql and it is product-db.sql (project name).

Btw what did you do in the plugin to remove the initial context being generated as folder and sql script?

2021-06-15 07:24 UTC, pa314159 commented on database/pom.xml
> +                        <stripComments>true</stripComments>
Hello @eacarvalho , [here](https://github.com/Backbase/blimp/commit/cfabfa313deb47c416764c8e88c7e5d26ad01392) is the commit.

2021-06-15 07:27 UTC, pa314159 commented on database/pom.xml
> +                        <stripComments>true</stripComments>
Or maybe [this](https://github.com/Backbase/blimp/blob/devel/README.md#withinitialversion) is clearer

2021-06-15 07:33 UTC, pa314159 commented on database/pom.xml
> +                        <stripComments>true</stripComments>
I wasn't sure there is an use case for [serviceName](https://github.com/Backbase/blimp#servicename) when I implemented it :)

The name is correct now.

2021-06-18 13:52 UTC, merged