add events
Backbase/golden-sample-services pull request #86
Opened 2021-07-14 12:04 UTC by bbzurek

Uplifted events branch

related to #7

2021-07-14 12:20 UTC, sophiejanssens approved these changes

2021-07-15 09:19 UTC, jjjasper commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +        EnvelopedEvent<com.backbase.product.event.spec.v1.ProductCreatedEvent> envelopedEvent = new EnvelopedEvent<>();
The ProductCreatedEvent is in import - should not need fully qualified classname here.

2021-07-15 09:19 UTC, jjjasper commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +        repository.findById(productId).ifPresent(productEntity -> {
The service does `findById` in the next line as well.

2021-07-15 09:35 UTC, fredysierra submitted a review, later dismissed

2021-07-16 08:09 UTC, jjjasper requested changes

2021-07-16 08:09 UTC, jjjasper commented on services/review/src/main/java/com/backbase/goldensample/review/mapper/EventMapper.java
> +    ReviewEntity eventToEntity(ProductCreatedEvent event);
This is too much business logic to be in a mapper.

2021-07-16 08:09 UTC, jjjasper commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
The mapper producing a complete review from the 'Store Admin' including 5* and 'we review and only add 5 star items to the store!' is really surprising.

2021-07-16 08:22 UTC, bbzurek commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
it's a made up scenario in a made up project..

2021-07-16 08:23 UTC, bbzurek commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
I mean we can change it to something else if you have any suggestions

2021-07-19 08:58 UTC, jjjasper commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
I understand it is a made up scenario and I do not object to this scenario; I object to implementing the scenario business logic in a class whose responsibility is "copying values from one object to another". It would be cleaner to put it in a `Service` class, in a method `createAutomatedAdminReview` or something like that.

2021-07-19 10:27 UTC, bbzurek commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
yes agreed, I was just updating that

2021-07-27 15:00 UTC, bbzurek commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +        ProductCreatedEvent event = mapper.entityToCreatedEvent(entityWithId);
yup makes sense

2021-07-27 15:00 UTC, bbzurek commented on services/product/src/main/java/com/backbase/goldensample/product/service/ProductServiceImpl.java
> +            // send event
done

2021-07-27 15:00 UTC, bbzurek commented on services/review/src/main/java/com/backbase/goldensample/review/listener/ProductCreateEventHandler.java
> +        ReviewEntity entity = eventMapper.eventToEntity(event);
refactored the scenario

2021-07-27 15:30 UTC, lehphyro approved these changes

2021-07-28 10:55 UTC, sophiejanssens approved these changes

2021-07-28 11:35 UTC, torrespro approved these changes

2021-07-28 11:35 UTC, merged